<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    App\ex00\Ex00::class => ['all' => true],
    App\ex01\Ex01::class => ['all' => true],
    App\ex02\Ex02::class => ['all' => true],
    App\ex03\Ex03::class => ['all' => true],
    App\ex04\Ex04::class => ['all' => true],
    App\ex05\Ex05::class => ['all' => true],
    App\ex06\Ex06::class => ['all' => true],
    App\ex07\Ex07::class => ['all' => true],
    App\ex08\Ex08::class => ['all' => true],
    App\ex09\Ex09::class => ['all' => true],
    App\ex10\Ex10::class => ['all' => true],
    App\ex11\Ex11::class => ['all' => true],
    App\ex12\Ex12::class => ['all' => true],
    App\ex13\Ex13::class => ['all' => true],
    App\ex14\Ex14::class => ['all' => true],
];
